openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"

  /register:
    post:
      requestBody:
        description: User registration
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: your.email@test.com
                  description: The user's email address.
                nickname:
                  type: string
                  example: nagibator228
                  description: The user's nickname.
                age:
                  type: integer
                  example: 95
                  description: The user's age.
                password:
                  type: string
                  format: password
                  example: secret12345(bad example)
                  description: The user's password.
              required:
                - email
                - nickname
                - age
                - password
      description: "Route to register new user"
      responses:
        "201":
          description: "CREATED"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "User TEST! was created"
        "409":
          description: "CONFLICT"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "USER ALREADY EXISTS"

  /login:
    post:
      requestBody:
        description: Login route
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: your.email@test.com
                  description: The user's email address.
                password:
                  type: string
                  format: password
                  example: secret12345
                  description: User's password
              required:
                - email
                - password
      description: "Route to login"
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token.
        401:
          description: Unauthorized - Wrong credentials
        406:
          description: Not Acceptable - Format not supported

  /user/all:
    get:
      description: "Get all users from db"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
        "401":
          description: "UNAUTHORIZED"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Access denied!"

  /user/{id}:
    get:
      description: "Get particular user by id"
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user.
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
        "401":
          description: "UNAUTHORIZED"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Access denied!"

  /user/profile:
    get:
      description: "Get current"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
        "401":
          description: "UNAUTHORIZED"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Access denied!"

components:
  schemas: { }