ktor:
  application:
    modules:
      - alexa.execute.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "http://0.0.0.0:8080/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password